### ISSUE TITLE
maps: js error (version 1.9.0)

### ISSUE THREAD

**Issue by vollyimnetz** [siteorigin/so-widgets-bundle#486]
Hi i got the following js error when using the maps-widget (after upgrade to version 1.9.0).

I tried to save the widget renew, but it did not change anything.
```
js-map.min.js?ver=1.9.0:1 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Object.<anonymous> (https://www.mypage.de/wp-content/plugins/so-widgets-bundle/widgets/google-map/js/js-map.min.js?ver=1.9.0:1:2848)
    at Object.showMarkers (https://www.mypage.de/wp-content/plugins/so-widgets-bundle/widgets/google-map/js/js-map.min.js?ver=1.9.0:1:3695)
    at Object.showMap (https://www.mypage.de/wp-content/plugins/so-widgets-bundle/widgets/google-map/js/js-map.min.js?ver=1.9.0:1:1156)
    at Object.<anonymous> (https://www.mypage.de/wp-content/plugins/so-widgets-bundle/widgets/google-map/js/js-map.min.js?ver=1.9.0:1:5233)
    at i (https://www.mypage.de/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:27449)
    at Object.fireWith [as resolveWith] (https://www.mypage.de/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:28213)
    at Object.e.(anonymous function) [as resolve] (https://www.mypage.de/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:29192)
    at Object.<anonymous> (https://www.mypage.de/wp-content/plugins/so-widgets-bundle/widgets/google-map/js/js-map.min.js?ver=1.9.0:1:6080)
    at https://maps.googleapis.com/maps-api-v3/api/js/29/2/intl/de_ALL/geocoder.js:5:191
    at https://maps.googleapis.com/maps-api-v3/api/js/29/2/intl/de_ALL/geocoder.js:3:246
```

**Comment by braamgenis** [comment]
Hi @vollyimnetz Thanks for letting us know. We'll get this fixed ASAP. I assume it's just not rendering your markers, but the map and everything else is still displaying as it should?

**Comment by vollyimnetz** [comment]
All is rendered properly
- Markers are present (i only used one)
- custom style working
- **marker is not clickable (infobox do not open)**

**Comment by braamgenis** [comment]
Ok, great. Thanks for your quick feedback! We'll get a fixed update out later today.

**Comment by andrejarh** [comment]
Experiencing same bug.
Custom marker doesn't show up in my case.

**Comment by braamgenis** [comment]
Hey guys. Apologies for the delay, but the fix update should be available now. Please let us know if you have any other issues!

**Comment by vollyimnetz** [comment]
Works like a charm. Thank you.
